
name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - '18'
          - '19'
          - '20'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout project sample-astro-pnpm
        uses: actions/checkout@v3
        with:
          repository: 'ghacts/sample-astro-pnpm'
          ref: main
          path: tests/astro

      - name: Test astro project
        uses: ./
        env:
          ASTRO_BASE_URL: 'http://localhost:3000/'
        with:
          project-path: tests/astro
          is-sub-path: true
          node-version: ${{ matrix.node-version }}
          artifact-name: "dist-astro-pnpm-${{ matrix.os }}-${{ matrix.node-version }}"
